#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

path_mode="/tmp/tmp/mode_test"
case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ -f "$path_mode" ]
	then
		#产测需要
		touch /tmp/tmp/reset_test
	else
		#正常的按键功能
		if [ "$SEEN" -lt 1 ]
		then
			if test -x /usr/sbin/reset-button; then
				/usr/sbin/reset-button
				return 0
			fi

			echo "REBOOT" > /dev/console
			sync
			reboot
		elif [ "$SEEN" -gt 5 -a -n "$OVERLAY" ]
		then
			echo "FACTORY RESET" > /dev/console
			jffs2reset -y && reboot &
		fi
	fi
;;
esac

return 0
