#!/bin/sh

. /lib/functions.sh


case "$ACTION" in
pressed)
	echo "WPS" > /dev/console
	iwpriv ra0 set WscConfMode=7
	iwpriv ra0 set WscMode=2
	iwpriv ra0 set WscGetConf=1
	
	echo timer > /sys/class/leds/WPS_LED/trigger
	echo 200 > /sys/class/leds/WPS_LED/delay_on
	echo 1400 > /sys/class/leds/WPS_LED/delay_off
;;
esac

return 0
