#!/bin/sh

. /lib/functions.sh

path_mode="/tmp/tmp/mode_test"
case "$ACTION" in
pressed)
	if [ -f "$path_mode" ]
	then
		#产测需要
		touch /tmp/tmp/wps_test
	else
		#正常的WPS功能
		echo "WPS" > /dev/console
		iwpriv ra0 set WscConfMode=7
		iwpriv ra0 set WscMode=2
		iwpriv ra0 set WscGetConf=1
	
		echo timer > /sys/class/leds/WPS_LED/trigger
		echo 200 > /sys/class/leds/WPS_LED/delay_on
		echo 1400 > /sys/class/leds/WPS_LED/delay_off
	fi
;;
esac

return 0
