#!/bin/sh

. /lib/functions.sh

case "$ACTION" in
pressed)
	echo "WPS" > /dev/console
	iwpriv ra0 set WscConfMode=7
	iwpriv ra0 set WscMode=2
	iwpriv ra0 set WscGetConf=1
	
	echo timer > /sys/class/leds/WPS_LED/trigger
	echo 200 > /sys/class/leds/WPS_LED/delay_on
	echo 1400 > /sys/class/leds/WPS_LED/delay_off
	
	int=1
	while true
	do
	let "int++"
	sleep 1
	dmesg -c
	iwpriv ra0 show stat
	result=`dmesg |grep WscState=0x4`
	echo $result > /dev/console
	if [[ "$result" != "" ]]
	then
		break
	fi
	if test $int -eq 50
	then
		break
	fi
done

echo 0 > /sys/class/leds/WPS_LED/delay_on

;;
esac

return 0
